name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy site into build folder
        run: |
          rm -rf build
          mkdir build
          cp -r src/* build/
          # include extra root files if they exist
          cp 404.html sitemap.xml robots.txt build/ || true
          echo "==== Build directory ===="
          tree -L 2 build || ls -R build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build       # what to publish
          branch: gh-pages    # where to publish
          clean: true 